import React from 'react';
import { FileText, Download, CheckCircle, Eye, ExternalLink, HardDrive, ShieldCheck } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { DriveService } from '../../../services/driveService';

export interface DocumentPreviewProps {
  id: string;
  title: string;
  templateName?: string;
  version?: string;
  status?: string;
  downloadUrl?: string;
  createdAt?: string;
  driveType?: 'MY_DRIVE' | 'PERSONAL' | 'TENANT_SHARED';
  parentId?: string | null;
  classification?: string;
  content?: string;
  onOpenInDocs?: (id: string) => void;
  onOpenInDrive?: (id: string, driveType?: string, parentId?: string | null) => void;
  onLivePreview?: (title: string, content: string) => void;
}

export const DocumentPreviewCard: React.FC<DocumentPreviewProps> = ({
  id,
  title,
  templateName = 'Aurora Document',
  version = 'v1.0',
  status: _status = 'active',
  downloadUrl,
  driveType = 'TENANT_SHARED',
  parentId = null,
  classification = 'INTERNAL',
  content = '',
  onOpenInDocs,
  onOpenInDrive,
  onLivePreview
}) => {
  const navigate = useNavigate();

  const handleOpenDocs = () => {
    try {
      DriveService.syncDriveItem({
        id,
        name: title,
        type: 'DOCUMENT',
        driveType: (driveType === 'MY_DRIVE' || driveType === 'PERSONAL') ? 'PERSONAL' : 'TENANT_SHARED',
        parentId: parentId || null,
        ownerId: 'ai-assistant',
        ownerName: 'Aurora AI Assistant',
        sizeBytes: (content || '').length * 2,
        content: content || `<h1>${title}</h1><p>Generated by Aurora AI Assistant</p>`,
        isFavorite: false,
        status: 'ACTIVE',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        recordsMetadata: {
          recordNumber: `REC-${new Date().getFullYear()}-${Math.floor(10000 + Math.random() * 90000)}`,
          classification: (classification as any) || 'INTERNAL',
          isLegalHold: false
        },
        versions: [],
        auditLogs: []
      });
    } catch (e) {
      console.warn('[DocumentPreviewCard] syncDriveItem warning:', e);
    }

    if (onOpenInDocs) {
      onOpenInDocs(id);
    } else {
      navigate(`/workspace/apps/docs/${id}`);
    }
  };

  const handleOpenDrive = () => {
    try {
      DriveService.syncDriveItem({
        id,
        name: title,
        type: 'DOCUMENT',
        driveType: (driveType === 'MY_DRIVE' || driveType === 'PERSONAL') ? 'PERSONAL' : 'TENANT_SHARED',
        parentId: parentId || null,
        ownerId: 'ai-assistant',
        ownerName: 'Aurora AI Assistant',
        sizeBytes: (content || '').length * 2,
        content: content || `<h1>${title}</h1><p>Generated by Aurora AI Assistant</p>`,
        isFavorite: false,
        status: 'ACTIVE',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        recordsMetadata: {
          recordNumber: `REC-${new Date().getFullYear()}-${Math.floor(10000 + Math.random() * 90000)}`,
          classification: (classification as any) || 'INTERNAL',
          isLegalHold: false
        },
        versions: [],
        auditLogs: []
      });
    } catch (e) {
      console.warn('[DocumentPreviewCard] syncDriveItem warning:', e);
    }

    const tab = (driveType === 'MY_DRIVE' || driveType === 'PERSONAL') ? 'PERSONAL' : 'TENANT_SHARED';
    const folderQuery = parentId ? `&folderId=${parentId}` : '';

    if (onOpenInDrive) {
      onOpenInDrive(id, driveType, parentId);
    } else {
      navigate(`/workspace/apps/drive?tab=${tab}${folderQuery}&selectedId=${id}`);
    }
  };

  const handlePreview = () => {
    if (onLivePreview) {
      onLivePreview(title, content);
    } else {
      toast.info(`Opening preview for "${title}"`);
    }
  };

  const handleDownload = () => {
    if (downloadUrl) {
      window.open(downloadUrl, '_blank');
      return;
    }
    const htmlBlob = new Blob([content || `<h1>${title}</h1>`], { type: 'text/html;charset=utf-8;' });
    const url = URL.createObjectURL(htmlBlob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success(`Downloaded "${title}.html"`);
  };

  return (
    <div className="my-3 overflow-hidden rounded-xl border border-indigo-500/30 bg-gradient-to-br from-zinc-900/95 via-zinc-900/90 to-indigo-950/40 p-4 shadow-xl backdrop-blur-md transition-all hover:border-indigo-500/60 group/card">
      <div className="flex items-start justify-between gap-3 border-b border-zinc-800/80 pb-3">
        <div className="flex items-start gap-3">
          <div className="rounded-xl bg-indigo-500/15 p-2.5 text-indigo-400 border border-indigo-500/30 shadow-inner group-hover/card:scale-105 transition-transform">
            <FileText className="h-6 w-6 text-indigo-400" />
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-[10px] font-mono font-bold tracking-wider text-indigo-400 uppercase bg-indigo-500/10 px-2 py-0.5 rounded border border-indigo-500/20">
                {templateName}
              </span>
              <span className="rounded bg-zinc-800 border border-zinc-700 px-1.5 py-0.2 text-[10px] font-mono text-zinc-300">
                {version}
              </span>
              <span className="flex items-center gap-1 rounded bg-teal-500/10 border border-teal-500/20 px-1.5 py-0.2 text-[10px] font-medium text-teal-300">
                <HardDrive className="h-2.5 w-2.5" />
                {driveType === 'MY_DRIVE' ? 'My Drive' : 'Tenant Shared'}
              </span>
            </div>
            <h4 className="text-sm font-semibold text-white mt-1.5 group-hover/card:text-indigo-200 transition-colors">
              {title}
            </h4>
          </div>
        </div>

        <div className="flex flex-col items-end gap-1">
          <span className="flex items-center gap-1 rounded-full bg-emerald-500/15 border border-emerald-500/30 px-2.5 py-0.5 text-[11px] text-emerald-400 font-medium shadow-sm">
            <CheckCircle className="h-3 w-3" />
            Saved to Drive
          </span>
          {classification && (
            <span className="flex items-center gap-1 text-[10px] font-mono text-zinc-400">
              <ShieldCheck className="h-3 w-3 text-indigo-400" />
              {classification}
            </span>
          )}
        </div>
      </div>

      {/* Action Bar */}
      <div className="mt-3 flex items-center justify-between text-xs text-zinc-400 pt-1 flex-wrap gap-2">
        <span className="text-[10.5px] text-zinc-500 font-mono truncate max-w-[150px]">
          ID: {id}
        </span>

        <div className="flex items-center gap-2 flex-wrap">
          {content && (
            <button
              onClick={handlePreview}
              className="flex items-center gap-1 rounded-lg border border-zinc-700/80 bg-zinc-800/90 px-2.5 py-1 text-[11.5px] font-medium text-zinc-200 hover:bg-zinc-700 hover:text-white transition cursor-pointer"
            >
              <Eye className="h-3.5 w-3.5 text-indigo-400" />
              <span>Preview</span>
            </button>
          )}

          <button
            onClick={handleOpenDrive}
            className="flex items-center gap-1 rounded-lg border border-teal-500/30 bg-teal-950/40 px-2.5 py-1 text-[11.5px] font-medium text-teal-300 hover:bg-teal-900/60 hover:text-teal-200 transition cursor-pointer"
          >
            <HardDrive className="h-3.5 w-3.5 text-teal-400" />
            <span>Drive</span>
          </button>

          <button
            onClick={handleOpenDocs}
            className="flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-1 font-medium text-[11.5px] text-white hover:bg-indigo-500 transition shadow cursor-pointer"
          >
            <ExternalLink className="h-3.5 w-3.5" />
            <span>Open in Docs</span>
          </button>

          <button
            onClick={handleDownload}
            className="flex items-center gap-1 rounded-lg border border-zinc-700 bg-zinc-800/80 px-2.5 py-1 text-[11.5px] font-medium text-zinc-300 hover:bg-zinc-700 hover:text-white transition cursor-pointer"
            title="Download Document HTML"
          >
            <Download className="h-3.5 w-3.5 text-zinc-400" />
          </button>
        </div>
      </div>
    </div>
  );
};

